app = "modix-server" # <<< здесь название твоего приложения (на Fly.io)

primary_region = "ams" # Амстердам (или другой ближайший регион)

[build]
dockerfile = "Dockerfile"

[env]
PORT = "5000"

[http_service]
internal_port = 5000
force_https = true
auto_stop_machines = true
auto_start_machines = true
